### ISSUE TITLE
Facing issues while generating events with SMASH

### ISSUE THREAD

**Issue by spadhan** [smash-transport/smash#49] opened 2023-01-12 12:26 UTC
Dear SMASH development team,
We wanted to generate events in Pb-Pb collisions in the TeV range, 
 however, it takes more than 160 hours to produce 4K events at 200 GeV. 
Is this a result of the event generators' nature or are there any settings that we are overlooking?
Would you kindly offer any suggestions on how to produce Pb-Pb collision events at the TeV scale?

Another problem we have is that when we try to build SMASH by incorporating ROOT software, an error occurs.

Thanks and regards,
Sonali

**Comment by AxelKrypton** [comment] 2023-01-12 13:31
@spadhan Thanks for opening the issue. In general, it is basically impossible to really help you without having more detailed information about what you attempted. SMASH is a complex codebase and its usage can be highly customised by the user via the configuration file.

More concretely, let me start from your last point. Which version of ROOT are you trying to use? With which version of SMASH? ...and, more importantly, which error did you get? About this point, it would help us to know which `cmake` command you used and its output together with the `make` command output if it is a compilation error. Maybe, you can also provide us with the output of `./smash -v` version, so that we know a bit more about your system.

Coming to SMASH being slow towards high energy, I would like to ask you the config file you used as input to run SMASH (if you want to attach it to your answer, please rename it with a `.txt` extension, since GitHub does not allow to upload `.yaml` files). We will then try to reproduce your large runtime on one of our machines. As side comment, it is known that SMASH slows down at high-energy collisions, and there is some work in the team to see whether and how easily that aspect could be mitigated.

Last but not least, a couple of side-notes. The upcoming release in few months will provide users with a largely improved codebase, also w.r.t. the user installation instructions. Problems with recent versions of ROOT, in particular, should naturally go away. About performance, we cannot make any guarantee, but I think it is worth mentioning that on supercomputers, depending on the machine at hand, it is in general possible and advantageous to run many instances of SMASH in the same and/or different jobs simultaneously with different random seeds and in the end combine the produced statistics (we call this _trivial parallelisation_). For example, in your mentioned case, running at the same time 10 instances of SMASH each producing 400 events would let you accumulate the same statistics in 16 hours. Furthermore, it sometimes happens on some clusters that the user gets assigned entire nodes only and, in this case, running in parallel as many SMASH instances as assigned cores is kind of "mandatory" in order not to waste resources.

**Comment by AxelKrypton** [comment] 2023-02-16 16:23
@spadhan We did not hear back anything from you. Without any further information from your side, which we would really like to have in order to help you, we cannot give you any additional hint and we will have to close this issue at some point.

**Comment by spadhan** [comment] 2023-02-20 11:49
Thank you for your response. I'm sorry for not getting back to you sooner. 
We are trying to install it in CentOS7 system .  previous problems have been resolved and now we are facing some new issues. we are trying to solve it by ourselves to learn new things in the process, we will let you know the details of the problem if we are unable to solve it.
Thanks and regards,
Sonali

**Comment by elfnerhannah** [comment] 2023-03-06 12:03
Sounds as if this issue can be closed for now.

**Closed by elfnerhannah** 2023-03-06 12:03 UTC
